import React from 'react';

/**
 * This was a component generated by LinkedIn resources
 *
 * @return {*} The linkedIn badge
 */
const LinkedInBadge = () => {
  return (
    <div
      className="badge-base LI-profile-badge"
      data-locale="en_US"
      data-size="medium"
      data-theme="dark"
      data-type="HORIZONTAL"
      data-vanity="jozek-hajduk"
      data-version="v1">
      <a className="badge-base__link LI-simple-link" href="https://co.linkedin.com/in/jozek-hajduk/en?trk=profile-badge"></a>
    </div>
  );
};

export { LinkedInBadge };
